bin/menmosd/Cargo.toml
bin/menmosd/tests/fixtures/mod.rs
bin/menmosd/tests/menmosd_query.rs
crates/apikit/src/reject.rs

Fix bad payload returning a 500 instead of a 400

---

bin/menmosd/src/menmosd/server/server_impl.rs
bin/menmosd/src/menmosd/server/ssl.rs

Fixes #19 
Un autre petit review :)

Fix sigint in HTTPS mode

---

bin/amphora/src/main.rs
bin/menmosd/src/main.rs
bin/menmosd/src/menmosd/server/server_impl.rs
bin/menmosd/src/menmosd/server/ssl.rs
crates/indexer/src/bitvec_tree.rs
crates/indexer/src/test/meta.rs

Fix silent failure on config load

---

bin/amphora/src/amphora/config.rs
bin/amphora/src/amphora/node/concurrent_repository.rs
bin/amphora/src/amphora/node/mod.rs
bin/amphora/src/amphora/node/node_impl.rs
bin/amphora/src/amphora/node/stringlock.rs
crates/menmos-client/src/client.rs

Protect blobs from data corruption caused by concurrent writes

---

Cargo.lock
bin/menmos-fuse/Cargo.toml
bin/menmos-fuse/src/omnifs/cached_client.rs
crates/lfan/Cargo.toml
crates/lfan/src/cache/cache.rs
crates/lfan/src/cache/concurrent_cache.rs
crates/lfan/src/cache/mod.rs
crates/lfan/src/cache/ttl_cache.rs
crates/lfan/src/lib.rs
crates/repository/Cargo.toml
crates/repository/src/s3/file_cache.rs

Add threadsafe cache & concurrent cache

---

bin/menmosd/release.toml
release.toml

Après ça je vais pouvoir taponner pour release nos premiers artifacts! 🎉

Add configurations for cargo-release

---

README.md
bin/amphora/src/amphora/config.rs
bin/amphora/src/amphora/node/node_impl.rs
bin/amphora/src/amphora/node/rebuild.rs
bin/menmosd/src/menmosd/config.rs
crates/testing/src/fixtures/data/amphora_http.toml
crates/testing/src/fixtures/data/menmosd_http.toml

Also removed old config keys that weren't used anymore

Add README

---

.github/workflows/ci.yml
.github/workflows/release.yml

Multiplatform builds

---

bin/amphora/src/amphora/node/directory_proxy.rs
bin/amphora/src/amphora/node/node_impl.rs
bin/menmosd/src/menmosd/node/node_impl.rs
bin/menmosd/src/menmosd/node/test/node.rs
bin/menmosd/src/menmosd/server/filters/blobmeta.rs
bin/menmosd/src/menmosd/server/handlers/blob/delete.rs
bin/menmosd/src/menmosd/server/handlers/blobmeta/delete.rs
bin/menmosd/src/menmosd/server/handlers/blobmeta/mod.rs
bin/menmosd/tests/menmosd_delete.rs
crates/interface/src/directory.rs

Add support for ACK on blob deletion

---

bin/menmosd/src/menmosd/server/filters/mod.rs

This PR enables the CORS when running menmosd in debug.

add support for cors in debug

---

bin/menmosd/src/menmosd/server/filters/mod.rs
crates/rapidquery/src/parser.rs

[MEN-43] - Fix CORS not being properly enabled in debug mode

---

bin/menmos-cli/src/cli/delete.rs
crates/menmos-repository/src/s3/repo.rs

- Fix clippy warnings and add username/password constraints
- Support piping blob IDs to the delete command
- Fix FIXME comment

[MEN-20] Support piping blob IDs to the delete CLI command

---

bin/menmosd/src/menmosd/node/routing/router.rs
crates/menmos-apikit/src/reject.rs
crates/menmos-std/src/collections/async_list.rs

- Fix race condition and add more error logging

[MEN-46] - Fix race condition in blob router

---

.github/workflows/ci.yml
.github/workflows/release.yml
Cargo.lock
Dockerfile
bin/amphora/Cargo.toml
bin/menmos-cli/Cargo.toml
bin/menmos-cli/src/cli/delete.rs
bin/menmos-cli/src/cli/download.rs
bin/menmos-cli/src/cli/mod.rs
bin/menmos-cli/src/cli/push.rs
bin/menmos-cli/src/cli/query.rs
bin/menmos-cli/src/main.rs
bin/menmosd/Cargo.toml
bin/menmosd/src/menmosd/node/routing/router.rs
bin/menmosd/src/menmosd/node/service/query.rs
crates/lfan/src/policy/insert_always.rs
crates/menmos-repository/src/s3/repo.rs
crates/menmos-xecute/Cargo.toml
crates/menmos-xecute/src/daemon.rs
justfile

included some version bumps & clippy fixes as well

[MEN-56] - Bundle menmos-web in production builds

---

bin/menmos-cli/src/service/query.rs

[MEN-72] - Fix CLI count bug

---

bin/menmosd/src/menmosd/node/routing/algorithm/min_size.rs

This only adds unit tests because testing this at the functional/integration level is _really_ cursed

[MEN-77] - Properly test the min-size policy

---

bin/menmosd/src/menmosd/node/service/indexer.rs
bin/menmosd/src/menmosd/node/service/query.rs
bin/menmosd/src/menmosd/node/store/meta.rs
bin/menmosd/src/menmosd/node/test/mock.rs
bin/menmosd/src/menmosd/node/test/node.rs
crates/menmos-interface/src/directory.rs
crates/menmos-interface/src/storage.rs
crates/menmos-protocol/src/directory.rs
crates/rapidquery/src/model.rs
crates/rapidquery/src/resolver.rs

Note: this breaks a few things. I created MEN-107 and MEN-108 to track the broken stuff, this way we'll fix them before the next release

[MEN-90] - Remove the parent field from the blob meta

---

bin/menmosd/src/menmosd/lib.rs
bin/menmosd/src/menmosd/node/service/query.rs
bin/menmosd/src/menmosd/node/store/bitvec_tree.rs
bin/menmosd/src/menmosd/node/store/documents.rs
bin/menmosd/src/menmosd/node/store/id_map.rs
bin/menmosd/src/menmosd/node/store/meta/fields.rs
bin/menmosd/src/menmosd/node/store/meta/interface.rs
bin/menmosd/src/menmosd/node/store/meta/mod.rs
bin/menmosd/src/menmosd/node/store/meta/sled_store.rs
bin/menmosd/src/menmosd/node/store/mod.rs
bin/menmosd/src/menmosd/node/test/node.rs
crates/menmos-interface/src/directory/dir.rs

Still need to address some TODOs before its ready but everything works!

[MEN-113] - Use a fieldName <=> fieldID mapping in the metadata map

---

Cargo.lock
crates/menmos-xecute/Cargo.toml
crates/menmos-xecute/src/logging.rs

I plan on adding such env overrides in menmosd and amphora in the future also

[MEN-135] - Allow overriding log level from env in xecute

---

bin/menmosd/src/menmosd/node/store/meta/fields.rs
bin/menmosd/src/menmosd/node/store/meta/sled_store.rs
bin/menmosd/tests/menmosd_query.rs
justfile

Fixed the bug, added test coverage and improved the tasks in the `justfile`

[MEN-132] - Fix case-insensitive queries

---

Cargo.lock
bin/amphora/Cargo.toml
bin/amphora/src/amphora/node/concurrent_repository.rs
bin/amphora/src/amphora/node/index.rs
bin/amphora/src/amphora/node/node_impl.rs
bin/amphora/src/amphora/node/transfer/worker.rs
bin/menmosd/src/menmosd/node/service/indexer.rs
bin/menmosd/src/menmosd/node/store/storage.rs
bin/menmosd/src/menmosd/node/test/mock.rs
crates/lfan/Cargo.toml
crates/lfan/src/cache/concurrent_cache.rs
crates/menmos-betterstreams/src/fs.rs
crates/menmos-repository/Cargo.toml
crates/menmos-repository/src/disk.rs
crates/menmos-repository/src/disk/mod.rs
crates/menmos-repository/src/disk/ops.rs
crates/menmos-repository/src/disk/repo.rs
crates/menmos-repository/src/iface.rs
crates/menmos-repository/src/lib.rs
crates/menmos-repository/src/s3/file_cache.rs
crates/menmos-repository/src/s3/repo.rs
crates/menmos-std/Cargo.toml
crates/menmos-std/src/lib.rs
crates/menmos-std/src/tx.rs

This is a big one. We discussed in person the design details of this so I won't outline them here.
This finishes the transaction system for the amphora, we still need to implement an equivalent system on the menmosd side (should be much simpler because its sled only)

[MEN-149] - Proto-transaction system for amphora

---

Cargo.lock
bin/amphora/Cargo.toml
bin/amphora/src/amphora/config.rs
bin/amphora/src/amphora/node/node_impl.rs
bin/amphora/src/amphora/server/layer.rs
crates/menmos-std/src/sync/sharded_mutex.rs

[MEN-158] - Add rate limiting and load shedding

---

bin/menmos-cli/src/cli/download.rs
bin/menmosd/src/menmosd/node/store/meta/fields.rs
bin/menmosd/tests/menmosd_query.rs
crates/menmos-interface/src/storage.rs

[MEN-118] - Add support for multivalue fields
